### PR TITLE
+  $ ./manage.py list_dynamic_fixtures

### PR DESCRIPTION
**Pull request by jedie**
I have made a django manage command to list all dynamic fixtures and the more important thing: To list every "skipped" fixtures.

e.g.: I didn't know that all apps skipped that has no "models.py" That was the reason to implement this ;)

A example output can be found here: https://gist.github.com/jedie/ac4370ff08a94a99082bea49d7715d17

### CODE REVIEW

**Comment by Peter-Slump** [comment]
Hi Jedie,

Thank you for your change! I'm happy to merge it however would you like to make the CI working? Otherwise I cannot merge the code.

Thanks in advance!

**Comment by jedie** [comment]
I fixed "flake8 checks" and add the same settings than django. Especially `max-line-length = 119` hope that's ok?!?

**Comment by jedie** [comment]
Tests still failed, because of backward-incompatibility...

What's about to skip test runs with not supported django versions?!? Say: `Django>=1.11`

And skip old Python versions, too?

**Comment by Peter-Slump** [comment]
@jedie I've added a --list argument in version 0.2.0 to list all fixtures. Please see the docs.

**Pull request closed without merging**
